version: '3'
services:
  asset:
    build:
      context: .
      dockerfile: Dockerfile-asset
    environment:
      AS_DATA_ROOT: /external/astool_storage
      AS_ASSET_ADDR: 0.0.0.0
      AS_ASSET_PORT: 30001
  utils:
    build:
      context: .
      dockerfile: Dockerfile-utils